
#Rock settings
[Rocks]
	rock = true
	granite_rock = true
	diorite_rock = true
	andesite_rock = true
	sand_rock = false
	red_sand_rock = false
	gravel_rock = false
	end_stone_rock = false
	netherrack_rock = false
	soul_soil_rock = false

#Stick settings
[Sticks]
	oak_stick = true
	spruce_stick = true
	birch_stick = true
	acacia_stick = true
	jungle_stick = true
	dark_oak_stick = true
	crimson_stick = false
	warped_stick = false

#Misc settings
[Misc]
	pinecone = true
	geyser = true
	nether_geyser = true
	seashell = true
	starfish = true
	underwater_seashell = true
	underwater_starfish = true

